<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function showCategory($slug)
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->join('c.posts', 'p')
            ->where('c.slug = :slug')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getResult();
    }
}
