app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

page404:
    path: /404
    defaults:
        _controller: FrameworkBundle:Template:template
        template: "@App/static/page404.html.twig"

login_check:
        path: /login_check

logout:
        path: /logout