# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
            ROLE_USER:        ROLE_USER
            ROLE_MODERATOR:   [ROLE_USER, ROLE_MODERATOR]
            ROLE_ADMIN:       [ROLE_MODERATOR, ROLE_ADMIN]

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: our_db_provider
                check_path: /login_check
                login_path: /login
                username_parameter: _username
                password_parameter: _password
            logout:
                path: /logout
                target: /
            anonymous: ~
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/admin/users, role: ROLE_ADMIN }
