<?php

namespace AppBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function showAllPost()
    {
        return $this->createQueryBuilder('p')
            ->select('p, c, t')
            ->join('p.category', 'c')
            ->join('p.tags', 't')
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();

    }

    public function showMostPopularPost()
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.createdAt')
            ->setFirstResult(1)
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
