<?php

namespace AppBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTags()
    {
        return $this->createQueryBuilder('t')
            ->select('t, p')
            ->leftJoin('t.posts', 'p')
           // ->orderBy('t.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function showNotNullTags()
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->join('t.posts', 'p')
            ->where('t.weightTag is NOT NULL')
            ->orderBy('t.weightTag', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
